language: node_js

node_js:
  - "10"

cache: yarn

script:
  - curl -O -s https://raw.githubusercontent.com/stratumn/groundcontrol/${TRAVIS_BRANCH}/schema.graphql || curl -O -s https://raw.githubusercontent.com/stratumn/groundcontrol/master/schema.graphql
  - yarn gen-ci
  - yarn test
  - yarn lint
